#!/bin/bash


#export DISPLAY=:20
#Xvfb :20 -screen 0 1366x768x16 &
#x11vnc -passwd TestVNC -display :20 -N -forever &

export DISPLAY=:01
Xvfb :01 -screen 0 1366x768x16 &
x11vnc -passwd TestVNC -display :01 -N -forever &
